sub: #æ³¨æœ‰#çš„æ˜¯å¤±æ•ˆçš„è®¢é˜…é“¾æ¥
# proxypoolèŠ‚ç‚¹æ± 
 # httpå¼€å¤´
  - https://sub.xeton.dev/sub?target=clash&url=https://tt.vg/freev2&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false #https://t.me/xrayfree
 # httpså¼€å¤´
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false #æ¯å¤©æ›´æ–°ï¼Œæ³¨æ„çœ‹æŠ“å–é€Ÿåº¦
 # GitHubæ‰˜ç®¡clashè®¢é˜…é“¾æ¥
# - https://kxswa.tk/clash #https://t.me/kxswa
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false #clashå…¬ç›Šå…è´¹èŠ‚ç‚¹è®¢é˜…æ¯å¤©æ›´æ–°
 # GitHubæ‰˜ç®¡b64è®¢é˜…é“¾æ¥
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/freefq/free/master/v2 #freev2
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2 #v2rayfree
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/Lewis-1217/FreeNodes/main/bpjzx1 #https://t.me/bpjzx1
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/Lewis-1217/FreeNodes/main/bpjzx2 #https://t.me/bpjzx2
 # GitLabæ‰˜ç®¡b64è®¢é˜…é“¾æ¥
# -  
# new add
# - https://raw.githubusercontent.com/anjue39/PoolActions/main/subscribe/clash.yaml
# - https://sub.xeton.dev/sub?target=clash&url=https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBdTJrVnZsREc4MU1oZ0puendMTVN5ZmljYmpnP2U9bVkzZ2ly&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false
  - https://proxy.yugogo.xyz/clash/proxies #ä¸é”™çš„å…è´¹ç«™ç‚¹ï¼Œæ¯å¤©æ›´æ–°ğŸš©
  - https://free.dsdog.tk/clash/proxies #ä¸é”™çš„å…è´¹ç«™ç‚¹ï¼Œæ¯å¤©æ›´æ–°ğŸš©
  - https://raw.githubusercontent.com/tbbatbb/Proxy/master/dist/clash.config.yaml #æ¯å¤©æ›´æ–°ï¼Œé‡Œé¢çš„æŠ“å–å·¥å…·å€¼å¾—ç ”ç©¶
# - https://sub.xeton.dev/sub?target=clash&url=http://weoknow.com/data/dayupdate/1/z1.txt&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false
# - https://sub.xeton.dev/sub?target=clash&url=http://weoknow.com/data/dayupdate/2/z1.txt&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false
  - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/snakem982/proxypool/main/clash28929.yaml #ğŸš©
  - https://wanshanziwo.eu.org/clash/proxies #ğŸš©
# - https://proxy.crazygeeky.com/clash/proxies #ğŸš©
  - https://free.jingfu.cf/clash/proxies
  - http://weoknow.com/data/dayupdate/1/z.yaml
  - http://weoknow.com/data/dayupdate/2/z.yaml
  - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml #ä¸é”™çš„å…è´¹ç«™ç‚¹ï¼Œæ¯å¤©æ›´æ–°ï¼Œé‡Œé¢æœ‰å¤§é‡åˆå¹¶çš„èŠ‚ç‚¹ï¼Œæœ‰listæºğŸš©
#
# - https://sub.xeton.dev/sub?target=clash&url=https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false #ğŸ±
# - https://sub.xeton.dev/sub?target=clash&url=https://prop.cf/?name=paimon&client=base64&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false #ğŸ±
# - https://sub.xeton.dev/sub?target=clash&url=https://youlianboshi.netlify.app&config=https://raw.githubusercontent.com/anjue39/openit/main/utils/subconverter/config/rule_mini.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false #ğŸ±
# - https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/clash/clash.provider.yaml #ğŸ±
# - https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/changfengoss.yaml #ğŸš©é•¿é£çš„
# - https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/combine.yaml #ğŸš©
# - https://api.dler.io/sub?target=clash&new_name=true&url=https://jiang.netlify.app #ğŸš©äºŒçˆ·ç¿»å¢™
# openit
# - https://ghproxy.com/https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml #å›ç¯è®¢é˜…
# - https://ghproxy.com/https://raw.githubusercontent.com/yu-steven/openit/main/utils/pool/pool.yaml #å…¥åº“è®¢é˜…
# openit
# - https://ghproxy.com/https://raw.githubusercontent.com/anjue39/openit/main/Clash.yaml #å›ç¯è®¢é˜…
# - https://ghproxy.com/https://raw.githubusercontent.com/anjue39/openit/main/utils/pool/pool.yaml #å…¥åº“è®¢é˜…
# TopPreeProxy
# - https://ghproxy.com/https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/sub/sub_merge_clash.yaml
local: ["into.yaml","../../Clash.yaml"] #åŒçº§ã€ä¸Šçº§æˆ–ä¸‹çº§ç›®å½•çš„æœ¬åœ°Clashé…ç½®æ–‡ä»¶ï¼Œä¸Šçº§ç›®å½•çš„æ–‡ä»¶éœ€è¦ä½¿ç”¨"../"è¿›è¡Œå¼•å¯¼
