name: Nodes_Diy

on: 
  # schedule: #UTC+0               #UTC+8
  #   - cron: '*/35 0-8 * * 1-5'   #工作日 上午8:00 - 下午4:00
  #   - cron: '*/25 8-14 * * 1-5'  #工作日 下午4:00 - 晚上10:00
  #   - cron: '*/55 14-21 * * 1-4' #工作日 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 21-23 * * 1-5' #工作日 次日凌晨5:00 - 次日上午8:00
  #   - cron: '*/25 14-21 * * 5'   #星期五 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 * * * 0,6'     #休息日 全天候
  # repository_dispatch: #https://www.chenshaowen.com/blog/how-to-trigger-github-action-remotely.html
    # types:
      # - Webhook
  workflow_dispatch: #手动调试按钮

jobs: 
  my-job: 
    name: Max Job
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3     #git clone
    - uses: actions/setup-node@v3   #Node.js环境
      with:
        node-version: '16.x'        #Node.js 16.x
    - name: Timezone #UTC+0 → UTC+8
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git
      run: | #配置git的上传用户名和邮箱
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: npm
      run: | #安装npm包
         cd ./utils/rm/
         npm ci
    - name: move urls #because ./utils/subconverter/generate.ini so input ./sub/url2
      run: mv ./sub/url2 > ./utils/rm/url #output ./utils/rm/url
    - name: remove & rename #input ./utils/rm/url
      run: cd ./utils/rm/ && npm start #output ./utils/rm/out
    - name: url & https
      run: | #input ./utils/rm/out
         rm ./utils/rm/url             #delete ./utils/rm/url
         mv ./utils/rm/out ./url       #output ./url
         ./.github/url.sh > ./1        #output ./1
         cp url 2                      #output ./2
         cat 1 2 > 3 && rm 1 2         #output ./3 & delete ./1 ./2
         base64 3 > https -w 0 && rm 3 #output ./https & delete ./3
         base64 ./url > ./utils/subconverter/base64 -w 0 #url文件base64编码引入subconverter
         sort url -o url #将url排序并修改至原文件，突出增删的节点 output ./url
    - name: long & Clash.yaml
      run: | #input ./utils/subconverter/base64 
         ./utils/subconverter/subconverter -g --artifact "clash"
         ./utils/subconverter/subconverter -g --artifact "long"
         ./utils/subconverter/subconverter -g --artifact "output"
         #output ./utils/subconverter/Clash.yaml ./utils/subconverter/long ./utils/subconverter/output.txt
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true #output ./Clash.yaml
         mv ./utils/subconverter/long ./long || true #output ./long
         rm ./utils/subconverter/base64 #delete ./utils/subconverter/base64
    - name: git push
      run: ./.github/update-repo.sh || true   #upload files ./url ./https ./long ./Clash.yaml to GitHub

  # Webhook: #触发Webhook启动下一次自动化
    # needs: my-job
    # runs-on: ubuntu-latest
    # steps:
    # - name: cURL
      # run: curl -s https://raw.githubusercontent.com/anjue39/openit/main/.github/webhook.sh | bash -s ${{ secrets.webhook }}
